---
- hosts: 172.31.2.159
  become: yes
  tasks: 
   - name: i want to execute any linux command directly 
     command: hostname -f
     register: myresult 

   - name: i want to debug
     debug: 
       msg: "{{myresult}}"
     

  
   