---
- hosts: 172.31.2.159
  become: yes
  tasks:
  - name: i want to execute any linux command directly  
    command: hostname -f
    register: myresult
  - name: display result
    debug:
      msg: "{{myresult}}"
  - name: insall git
    apt: 
      name: git
      state: present
    when: myresult.stderr==""

  - name: install tree
    apt:
      name: tree
      state: present 
    when: myresult.stderr !=""

  - name: install wget
    apt: 
      name: wget
      state: present
    when: myresult.stderr==""
    



