---
- hosts: 172.31.12.159
  become: yes
  tasks:
   - name: i want to execute any linux command directly 
     command: hostname -f 
   - name: i want to debug
     debug: 
     msg: "{myresult}"
     register: myresult