---
- hosts: 172.31.12.159
  become: yes
  tasks: 
   - name: install git 
     apt: 
      name: git
      state: present

   - name: install tree 
     apt: 
      name: tree
      stateeeee: present
      ignore_error: yes

   - name: install wget 
     apt: 
      name: wget
      state: present